apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
spec:
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: {{ .Release.Name }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect